package com.digitalamanmedia.bhumistar.persentation.screens.profile.utils

object GetDistrict {
    fun getDistrict(state:String):List<String>{
        return when(state){
            "Andhra Pradesh"->StateAndDistrict.getAndhraPradesh()
            "Arunachal Pradesh"->StateAndDistrict.getArunachalPradesh()
            "Assam"->StateAndDistrict.getAssam()
            "Bihar"->StateAndDistrict.getBihar()
            "Chhattisgarh"->StateAndDistrict.getChhattisgarh()
            "Goa"->StateAndDistrict.getGoa()
            "Gujarat"->StateAndDistrict.getGujarat()
            "Haryana"->StateAndDistrict.getHaryana()
            "Himachal Pradesh"->StateAndDistrict.getHimachalPradesh()
            "Jammu and Kashmir"->StateAndDistrict.getJammuAndKashmir()
            "Jharkhand"->StateAndDistrict.getJharkhand()
            "Karnataka"->StateAndDistrict.getKarnataka()
            "Kerala"->StateAndDistrict.getKerala()
            "Madhya Pradesh"->StateAndDistrict.getMadhyaPradesh()
            "Maharashtra"->StateAndDistrict.getMaharashtra()
            "Manipur"->StateAndDistrict.getManipur()
            "Meghalaya"->StateAndDistrict.getMeghalaya()
            "Mizoram"->StateAndDistrict.getMizoram()
            "Nagaland"->StateAndDistrict.getNagaland()
            "Odisha"->StateAndDistrict.getOdisha()
            "Punjab"->StateAndDistrict.getPunjab()
            "Rajasthan"->StateAndDistrict.getRajasthan()
            "Sikkim"->StateAndDistrict.getSikkim()
            "Tamil Nadu"->StateAndDistrict.getTamilNadu()
            "Telangana"->StateAndDistrict.getTelangana()
            "Tripura"->StateAndDistrict.getTripura()
            "Uttarakhand"->StateAndDistrict.getUttarakhand()
            "Uttar Pradesh"->StateAndDistrict.getUttarPradesh()
            "West Bengal"->StateAndDistrict.getWestBengal()
            "Andaman and Nicobar Islands"->StateAndDistrict.getAndamanAndNicobarIsland()
            "Chandigarh"->StateAndDistrict.getChandigarh()
            "Dadra and Nagar Haveli"->StateAndDistrict.getDadraAndNagarHaveli()
            "Daman and Diu"->StateAndDistrict.getDamanAndDiu()
            "Delhi"->StateAndDistrict.getDelhi()
            "Lakshadweep"->StateAndDistrict.getLakshadweep()
            "Pondicherry"->StateAndDistrict.getPondicherry()
            else -> emptyList()
        }
    }
}